-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 15, 2021 at 12:36 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 7.3.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `max_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogpost`
--

CREATE TABLE `blogpost` (
  `id` int(11) NOT NULL,
  `title` varchar(256) NOT NULL,
  `content` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `blogpost`
--

INSERT INTO `blogpost` (`id`, `title`, `content`) VALUES
(1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque', 'Laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'),
(3, 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis', 'Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.'),
(4, 'Sed ligula velit, lobortis nec elementum non, eleifend nec turpis', 'Suspendisse potenti. Quisque fermentum justo sit amet tellus interdum, sagittis mollis arcu interdum. Sed vehicula ligula tortor, vel cursus nisi suscipit convallis. Curabitur faucibus metus purus, at vulputate est varius eu. In nec orci ante. Nulla tincidunt, libero eget sollicitudin consectetur, erat dui commodo sem, ac pellentesque lectus ligula ac mi. Donec at nulla eu tortor tempus tempus vitae in metus. Curabitur vestibulum ullamcorper nisi, eu congue nibh posuere id. Vestibulum a velit auctor, accumsan tortor quis, auctor lorem. Aliquam quam libero, dictum ut sem quis, auctor sodales lacus. Vestibulum scelerisque neque vitae arcu sollicitudin, ornare rhoncus libero ornare. Aliquam rutrum nulla sed ante convallis fermentum. Suspendisse potenti. Quisque fermentum justo sit amet tellus interdum, sagittis mollis arcu interdum. Sed vehicula ligula tortor, vel cursus nisi suscipit convallis. Curabitur faucibus metus purus, at vulputate est varius eu. In nec orci ante. Nulla tincidunt, libero eget sollicitudin consectetur, erat dui commodo sem, ac pellentesque lectus ligula ac mi. Donec at nulla eu tortor tempus tempus vitae in metus. Curabitur vestibulum ullamcorper nisi, eu congue nibh posuere id. Vestibulum a velit auctor, accumsan tortor quis, auctor lorem. Aliquam quam libero, dictum ut sem quis, auctor sodales lacus. Vestibulum scelerisque neque vitae arcu sollicitudin, ornare rhoncus libero ornare. Aliquam rutrum nulla sed ante convallis fermentum. Suspendisse potenti. Quisque fermentum justo sit amet tellus interdum, sagittis mollis arcu interdum. Sed vehicula ligula tortor, vel cursus nisi suscipit convallis. Curabitur faucibus metus purus, at vulputate est varius eu. In nec orci ante. Nulla tincidunt, libero eget sollicitudin consectetur, erat dui commodo sem, ac pellentesque lectus ligula ac mi. Donec at nulla eu tortor tempus tempus vitae in metus. Curabitur vestibulum ullamcorper nisi, eu congue nibh posuere id. Vestibulum a velit auctor, accumsan tortor quis, auctor lorem. Aliquam quam libero, dictum ut sem quis, auctor sodales lacus. Vestibulum scelerisque neque vitae arcu sollicitudin, ornare rhoncus libero ornare. Aliquam rutrum nulla sed ante convallis fermentum.'),
(5, 'Ut rhoncus risus et tellus tempus pulvinar', 'Aenean sed pretium est, vehicula pretium neque. Etiam rhoncus vestibulum scelerisque. Cras tellus massa, molestie dictum rutrum id, vestibulum nec urna. Sed et tristique tellus. Pellentesque eget diam id ligula faucibus fermentum. Curabitur venenatis turpis elit, vitae euismod arcu pharetra sed. Integer condimentum, nisi quis fermentum semper, dolor sapien placerat arcu, ut feugiat velit libero id ante. Nullam sit amet est sit amet sem lacinia eleifend. In ut velit quam. Nunc porttitor dignissim felis. Quisque nisi risus, sodales non arcu vel, condimentum ultricies ipsum. Maecenas rhoncus ante nec ipsum pharetra, vitae hendrerit arcu pellentesque. Sed vitae mauris ac tellus dictum condimentum sed sit amet turpis. Sed pellentesque mi ut finibus laoreet. Nulla vel tellus euismod metus facilisis aliquam. Aenean sed pretium est, vehicula pretium neque. Etiam rhoncus vestibulum scelerisque. Cras tellus massa, molestie dictum rutrum id, vestibulum nec urna. Sed et tristique tellus. Pellentesque eget diam id ligula faucibus fermentum. Curabitur venenatis turpis elit, vitae euismod arcu pharetra sed. Integer condimentum, nisi quis fermentum semper, dolor sapien placerat arcu, ut feugiat velit libero id ante. Nullam sit amet est sit amet sem lacinia eleifend. In ut velit quam. Nunc porttitor dignissim felis. Quisque nisi risus, sodales non arcu vel, condimentum ultricies ipsum. Maecenas rhoncus ante nec ipsum pharetra, vitae hendrerit arcu pellentesque. Sed vitae mauris ac tellus dictum condimentum sed sit amet turpis. Sed pellentesque mi ut finibus laoreet. Nulla vel tellus euismod metus facilisis aliquam. Aenean sed pretium est, vehicula pretium neque. Etiam rhoncus vestibulum scelerisque. Cras tellus massa, molestie dictum rutrum id, vestibulum nec urna. Sed et tristique tellus. Pellentesque eget diam id ligula faucibus fermentum. Curabitur venenatis turpis elit, vitae euismod arcu pharetra sed. Integer condimentum, nisi quis fermentum semper, dolor sapien placerat arcu, ut feugiat velit libero id ante. Nullam sit amet est sit amet sem lacinia eleifend. In ut velit quam. Nunc porttitor dignissim felis. Quisque nisi risus, sodales non arcu vel, condimentum ultricies ipsum. Maecenas rhoncus ante nec ipsum pharetra, vitae hendrerit arcu pellentesque. Sed vitae mauris ac tellus dictum condimentum sed sit amet turpis. Sed pellentesque mi ut finibus laoreet. Nulla vel tellus euismod metus facilisis aliquam.'),
(6, 'In rhoncus velit non fringilla accumsan. Nunc a nisi efficitur, pretium urna nec, ultricies nisl', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed egestas posuere mollis. In hac habitasse platea dictumst. Phasellus pellentesque tortor nec sem ornare mattis. Cras condimentum nec neque eu cursus. Donec fermentum augue vel tellus cursus, non sodales metus mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed egestas posuere mollis. In hac habitasse platea dictumst. Phasellus pellentesque tortor nec sem ornare mattis. Cras condimentum nec neque eu cursus. Donec fermentum augue vel tellus cursus, non sodales metus mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed egestas posuere mollis. In hac habitasse platea dictumst. Phasellus pellentesque tortor nec sem ornare mattis. Cras condimentum nec neque eu cursus. Donec fermentum augue vel tellus cursus, non sodales metus mattis.'),
(7, 'Fusce quam odio, consequat ac velit vel, convallis laoreet ipsum', 'Maecenas volutpat non ante vitae finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In faucibus sapien ante, vel congue nibh pharetra eget. Donec ut lectus auctor, fermentum quam in, luctus tellus. Fusce bibendum ultricies leo, vitae interdum est aliquam ut. Suspendisse sit amet nulla a nulla luctus egestas. Fusce condimentum est et libero volutpat lacinia. In auctor felis vitae rutrum cursus. Phasellus at odio eros. Sed iaculis nunc orci, et fringilla diam pellentesque at. Maecenas volutpat non ante vitae finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In faucibus sapien ante, vel congue nibh pharetra eget. Donec ut lectus auctor, fermentum quam in, luctus tellus. Fusce bibendum ultricies leo, vitae interdum est aliquam ut. Suspendisse sit amet nulla a nulla luctus egestas. Fusce condimentum est et libero volutpat lacinia. In auctor felis vitae rutrum cursus. Phasellus at odio eros. Sed iaculis nunc orci, et fringilla diam pellentesque at. Maecenas volutpat non ante vitae finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In faucibus sapien ante, vel congue nibh pharetra eget. Donec ut lectus auctor, fermentum quam in, luctus tellus. Fusce bibendum ultricies leo, vitae interdum est aliquam ut. Suspendisse sit amet nulla a nulla luctus egestas. Fusce condimentum est et libero volutpat lacinia. In auctor felis vitae rutrum cursus. Phasellus at odio eros. Sed iaculis nunc orci, et fringilla diam pellentesque at.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogpost`
--
ALTER TABLE `blogpost`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogpost`
--
ALTER TABLE `blogpost`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
